import { db } from "./db";
import { products } from "./db/schema";

const seedProducts = [
  // ─── CPU ──────────────────────────────────────────────────────
  {
    name: "Intel Core i9-14900K",
    category: "CPU",
    description: "24-core flagship desktop processor (8P+16E) รองรับ DDR5 และ DDR4 เหมาะสำหรับ gaming และ content creation ระดับสูงสุด",
    price: 19900,
    imageUrl: "",
    stock: 15,
    attributes: {
      componentType: "CPU",
      socket: "LGA1700",
      cores: 24,
      threads: 32,
      baseClock: 3.2,
      boostClock: 6.0,
      tdp: 125,
      integratedGraphics: true,
    },
  },
  {
    name: "Intel Core i7-14700K",
    category: "CPU",
    description: "20-core processor (8P+12E) สมรรถนะสูงในราคาที่เข้าถึงได้ เหมาะกับ gaming และ multitasking",
    price: 13500,
    imageUrl: "",
    stock: 20,
    attributes: {
      componentType: "CPU",
      socket: "LGA1700",
      cores: 20,
      threads: 28,
      baseClock: 3.4,
      boostClock: 5.6,
      tdp: 125,
      integratedGraphics: true,
    },
  },
  {
    name: "Intel Core i5-14600K",
    category: "CPU",
    description: "14-core processor (6P+8E) ตัวเลือกยอดนิยมสำหรับ gaming ราคาคุ้มค่า",
    price: 8900,
    imageUrl: "",
    stock: 30,
    attributes: {
      componentType: "CPU",
      socket: "LGA1700",
      cores: 14,
      threads: 20,
      baseClock: 3.5,
      boostClock: 5.3,
      tdp: 125,
      integratedGraphics: true,
    },
  },
  {
    name: "AMD Ryzen 9 7950X",
    category: "CPU",
    description: "16-core workstation-class processor บน AM5 platform พร้อม DDR5 ประสิทธิภาพสูงสุดสำหรับงาน 3D rendering และ video editing",
    price: 21500,
    imageUrl: "",
    stock: 10,
    attributes: {
      componentType: "CPU",
      socket: "AM5",
      cores: 16,
      threads: 32,
      baseClock: 4.5,
      boostClock: 5.7,
      tdp: 170,
      integratedGraphics: false,
    },
  },
  {
    name: "AMD Ryzen 7 7700X",
    category: "CPU",
    description: "8-core AM5 processor ประสิทธิภาพดีเยี่ยมสำหรับ gaming และงาน creative ในราคากลาง",
    price: 9500,
    imageUrl: "",
    stock: 25,
    attributes: {
      componentType: "CPU",
      socket: "AM5",
      cores: 8,
      threads: 16,
      baseClock: 4.5,
      boostClock: 5.4,
      tdp: 105,
      integratedGraphics: false,
    },
  },
  {
    name: "AMD Ryzen 5 7600X",
    category: "CPU",
    description: "6-core AM5 processor ตัวเลือกที่ดีที่สุดในราคาประหยัดสำหรับ gaming",
    price: 6500,
    imageUrl: "",
    stock: 35,
    attributes: {
      componentType: "CPU",
      socket: "AM5",
      cores: 6,
      threads: 12,
      baseClock: 4.7,
      boostClock: 5.3,
      tdp: 105,
      integratedGraphics: false,
    },
  },

  // ─── Mainboard ────────────────────────────────────────────────
  {
    name: "ASUS ROG Maximus Z790 Hero",
    category: "Mainboard",
    description: "High-end Z790 ATX motherboard สำหรับ Intel LGA1700 พร้อม DDR5, PCIe 5.0 และ Wi-Fi 6E",
    price: 18500,
    imageUrl: "",
    stock: 8,
    attributes: {
      componentType: "Mainboard",
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memoryType: "DDR5",
      ramSlots: 4,
      hasWifi: true,
    },
  },
  {
    name: "MSI MAG B760 Tomahawk WiFi",
    category: "Mainboard",
    description: "B760 ATX motherboard คุ้มค่า รองรับ Intel LGA1700 พร้อม DDR5 และ Wi-Fi 6E เหมาะกับ build งบกลาง",
    price: 5900,
    imageUrl: "",
    stock: 20,
    attributes: {
      componentType: "Mainboard",
      socket: "LGA1700",
      chipset: "B760",
      formFactor: "ATX",
      memoryType: "DDR5",
      ramSlots: 4,
      hasWifi: true,
    },
  },
  {
    name: "ASUS ROG Crosshair X670E Hero",
    category: "Mainboard",
    description: "Flagship X670E ATX motherboard สำหรับ AMD AM5 พร้อม PCIe 5.0 x16, DDR5 และ Wi-Fi 6E",
    price: 19900,
    imageUrl: "",
    stock: 6,
    attributes: {
      componentType: "Mainboard",
      socket: "AM5",
      chipset: "X670E",
      formFactor: "ATX",
      memoryType: "DDR5",
      ramSlots: 4,
      hasWifi: true,
    },
  },
  {
    name: "MSI PRO B650-P WiFi",
    category: "Mainboard",
    description: "B650 ATX motherboard ราคาประหยัดสำหรับ AMD AM5 รองรับ DDR5 และ Wi-Fi 6",
    price: 4900,
    imageUrl: "",
    stock: 22,
    attributes: {
      componentType: "Mainboard",
      socket: "AM5",
      chipset: "B650",
      formFactor: "ATX",
      memoryType: "DDR5",
      ramSlots: 4,
      hasWifi: true,
    },
  },

  // ─── RAM ──────────────────────────────────────────────────────
  {
    name: "G.Skill Trident Z5 RGB DDR5-6000 32GB (2x16GB)",
    category: "RAM",
    description: "High-performance DDR5 kit ความเร็ว 6000 MHz CL30 พร้อม RGB lighting สวยงาม",
    price: 5200,
    imageUrl: "",
    stock: 18,
    attributes: {
      componentType: "RAM",
      memoryType: "DDR5",
      capacity: 32,
      modules: 2,
      speed: 6000,
      casLatency: 30,
    },
  },
  {
    name: "Corsair Vengeance DDR5-5600 32GB (2x16GB)",
    category: "RAM",
    description: "Reliable DDR5 kit ความเร็ว 5600 MHz เหมาะสำหรับ AM5 และ LGA1700 platform",
    price: 3900,
    imageUrl: "",
    stock: 25,
    attributes: {
      componentType: "RAM",
      memoryType: "DDR5",
      capacity: 32,
      modules: 2,
      speed: 5600,
      casLatency: 36,
    },
  },
  {
    name: "Kingston Fury Beast DDR4-3200 16GB (2x8GB)",
    category: "RAM",
    description: "Budget-friendly DDR4 kit ความเร็ว 3200 MHz เหมาะสำหรับ platform LGA1700 ที่ยังใช้ DDR4",
    price: 1590,
    imageUrl: "",
    stock: 40,
    attributes: {
      componentType: "RAM",
      memoryType: "DDR4",
      capacity: 16,
      modules: 2,
      speed: 3200,
      casLatency: 16,
    },
  },

  // ─── GPU ──────────────────────────────────────────────────────
  {
    name: "ASUS ROG Strix GeForce RTX 4090 OC 24GB",
    category: "GPU",
    description: "การ์ดจอ flagship ประสิทธิภาพสูงสุด เหมาะสำหรับ 4K gaming, 3D rendering และ AI workloads",
    price: 69900,
    imageUrl: "",
    stock: 5,
    attributes: {
      componentType: "GPU",
      chipset: "GeForce RTX 4090",
      vram: 24,
      length: 357,
      recommendedPsu: 850,
    },
  },
  {
    name: "MSI Gaming X Slim GeForce RTX 4080 Super 16GB",
    category: "GPU",
    description: "High-end GPU สำหรับ 4K gaming ราคาสมเหตุสมผลกว่า RTX 4090 ประสิทธิภาพยอดเยี่ยม",
    price: 39900,
    imageUrl: "",
    stock: 8,
    attributes: {
      componentType: "GPU",
      chipset: "GeForce RTX 4080 Super",
      vram: 16,
      length: 337,
      recommendedPsu: 750,
    },
  },
  {
    name: "Gigabyte Eagle GeForce RTX 4070 Ti Super 16GB",
    category: "GPU",
    description: "Mid-to-high range GPU เหมาะสำหรับ 1440p และ 4K gaming ในราคาที่เข้าถึงได้",
    price: 27500,
    imageUrl: "",
    stock: 12,
    attributes: {
      componentType: "GPU",
      chipset: "GeForce RTX 4070 Ti Super",
      vram: 16,
      length: 300,
      recommendedPsu: 700,
    },
  },
  {
    name: "Sapphire Nitro+ AMD Radeon RX 7900 XTX 24GB",
    category: "GPU",
    description: "AMD flagship GPU สำหรับ 4K gaming พร้อม 24GB GDDR6 memory ประสิทธิภาพแข่งขันกับ RTX 4080",
    price: 35900,
    imageUrl: "",
    stock: 7,
    attributes: {
      componentType: "GPU",
      chipset: "Radeon RX 7900 XTX",
      vram: 24,
      length: 336,
      recommendedPsu: 800,
    },
  },
  {
    name: "ASUS Dual GeForce RTX 4060 8GB OC",
    category: "GPU",
    description: "Entry-level RTX 4060 เหมาะสำหรับ 1080p gaming ประหยัดพลังงาน TDP เพียง 115W",
    price: 10900,
    imageUrl: "",
    stock: 20,
    attributes: {
      componentType: "GPU",
      chipset: "GeForce RTX 4060",
      vram: 8,
      length: 240,
      recommendedPsu: 550,
    },
  },

  // ─── SSD ──────────────────────────────────────────────────────
  {
    name: "Samsung 990 Pro 2TB NVMe PCIe 4.0",
    category: "SSD",
    description: "High-performance M.2 SSD ความเร็วอ่านสูงสุด 7,450 MB/s เหมาะสำหรับ gaming และ content creation",
    price: 4290,
    imageUrl: "",
    stock: 30,
    attributes: {
      componentType: "SSD",
      formFactor: "M.2 2280",
      interface: "PCIe 4.0 x4",
      capacity: 2000,
      readSpeed: 7450,
      writeSpeed: 6900,
    },
  },
  {
    name: "WD Black SN850X 1TB NVMe PCIe 4.0",
    category: "SSD",
    description: "Gaming-optimized NVMe SSD ความเร็วอ่านสูงสุด 7,300 MB/s พร้อม Game Mode 2.0",
    price: 2490,
    imageUrl: "",
    stock: 35,
    attributes: {
      componentType: "SSD",
      formFactor: "M.2 2280",
      interface: "PCIe 4.0 x4",
      capacity: 1000,
      readSpeed: 7300,
      writeSpeed: 6300,
    },
  },
  {
    name: "Seagate FireCuda 530 2TB NVMe PCIe 4.0",
    category: "SSD",
    description: "High-endurance NVMe SSD ความเร็วสูงสุด 7,300 MB/s เหมาะสำหรับ workstation และ gaming",
    price: 4590,
    imageUrl: "",
    stock: 15,
    attributes: {
      componentType: "SSD",
      formFactor: "M.2 2280",
      interface: "PCIe 4.0 x4",
      capacity: 2000,
      readSpeed: 7300,
      writeSpeed: 6900,
    },
  },
  {
    name: "Crucial T705 1TB NVMe PCIe 5.0",
    category: "SSD",
    description: "PCIe 5.0 SSD รุ่นใหม่ล่าสุด ความเร็วอ่านสูงสุดถึง 13,600 MB/s",
    price: 3990,
    imageUrl: "",
    stock: 10,
    attributes: {
      componentType: "SSD",
      formFactor: "M.2 2280",
      interface: "PCIe 5.0 x4",
      capacity: 1000,
      readSpeed: 13600,
      writeSpeed: 10200,
    },
  },

  // ─── PSU ──────────────────────────────────────────────────────
  {
    name: "Corsair HX1000i 1000W 80+ Platinum",
    category: "PSU",
    description: "Fully modular 1000W PSU ประสิทธิภาพ 80+ Platinum เหมาะสำหรับ high-end build พร้อม RTX 4090",
    price: 7900,
    imageUrl: "",
    stock: 12,
    attributes: {
      componentType: "PSU",
      wattage: 1000,
      efficiency: "80+ Platinum",
      modularity: "Full",
      formFactor: "ATX",
    },
  },
  {
    name: "be quiet! Dark Power 13 850W 80+ Titanium",
    category: "PSU",
    description: "Ultra-efficient 850W Titanium PSU เงียบเป็นพิเศษ เหมาะสำหรับ silent build คุณภาพสูง",
    price: 8500,
    imageUrl: "",
    stock: 8,
    attributes: {
      componentType: "PSU",
      wattage: 850,
      efficiency: "80+ Titanium",
      modularity: "Full",
      formFactor: "ATX",
    },
  },
  {
    name: "Seasonic Focus GX-750 750W 80+ Gold",
    category: "PSU",
    description: "Fully modular 750W Gold PSU คุณภาพดี เหมาะสำหรับ mid-range build พร้อม RTX 4070",
    price: 4200,
    imageUrl: "",
    stock: 20,
    attributes: {
      componentType: "PSU",
      wattage: 750,
      efficiency: "80+ Gold",
      modularity: "Full",
      formFactor: "ATX",
    },
  },
  {
    name: "Cooler Master MWE 650 Bronze V2 650W",
    category: "PSU",
    description: "Semi-modular 650W PSU ราคาประหยัด เหมาะสำหรับ budget build ที่ใช้ RTX 4060 หรือต่ำกว่า",
    price: 1990,
    imageUrl: "",
    stock: 30,
    attributes: {
      componentType: "PSU",
      wattage: 650,
      efficiency: "80+ Bronze",
      modularity: "Semi",
      formFactor: "ATX",
    },
  },

  // ─── Case ─────────────────────────────────────────────────────
  {
    name: "Lian Li PC-O11 Dynamic EVO",
    category: "Case",
    description: "Mid Tower case ยอดนิยม กระจกใส 3 ด้าน รองรับ ATX/Micro-ATX/Mini-ITX และ 420mm radiator",
    price: 5500,
    imageUrl: "",
    stock: 15,
    attributes: {
      componentType: "Case",
      formFactor: "Mid Tower",
      motherboardSupport: ["ATX", "Micro-ATX", "Mini-ITX"],
      maxGpuLength: 420,
      maxCpuCoolerHeight: 167,
    },
  },
  {
    name: "Fractal Design Meshify 2 XL",
    category: "Case",
    description: "Full Tower case airflow ดีเยี่ยม mesh front panel รองรับ E-ATX และ radiator ขนาด 420mm",
    price: 6900,
    imageUrl: "",
    stock: 8,
    attributes: {
      componentType: "Case",
      formFactor: "Full Tower",
      motherboardSupport: ["E-ATX", "ATX", "Micro-ATX", "Mini-ITX"],
      maxGpuLength: 467,
      maxCpuCoolerHeight: 185,
    },
  },
  {
    name: "NZXT H510 Flow",
    category: "Case",
    description: "Compact Mid Tower case ดีไซน์สวยงาม airflow ดี เหมาะสำหรับ build ขนาดกะทัดรัด",
    price: 3200,
    imageUrl: "",
    stock: 18,
    attributes: {
      componentType: "Case",
      formFactor: "Mid Tower",
      motherboardSupport: ["ATX", "Micro-ATX", "Mini-ITX"],
      maxGpuLength: 381,
      maxCpuCoolerHeight: 165,
    },
  },

  // ─── CPU Cooler ───────────────────────────────────────────────
  {
    name: "Noctua NH-D15 chromax.black",
    category: "CPU Cooler",
    description: "Dual-tower air cooler ประสิทธิภาพสูงสุดในบรรดา air cooler เงียบมาก รองรับ LGA1700 และ AM5",
    price: 3200,
    imageUrl: "",
    stock: 15,
    attributes: {
      componentType: "CPU Cooler",
      type: "Air Cooler",
      socketSupport: ["LGA1700", "LGA1200", "AM5", "AM4"],
      height: 165,
    },
  },
  {
    name: "ARCTIC Liquid Freezer III 360",
    category: "CPU Cooler",
    description: "360mm AIO liquid cooler ประสิทธิภาพเยี่ยมในราคาคุ้มค่า เหมาะสำหรับ i9/Ryzen 9",
    price: 3500,
    imageUrl: "",
    stock: 12,
    attributes: {
      componentType: "CPU Cooler",
      type: "Liquid Cooler",
      socketSupport: ["LGA1700", "LGA1200", "AM5", "AM4"],
      radiatorSize: 360,
    },
  },
  {
    name: "Corsair iCUE H150i Elite LCD 360mm",
    category: "CPU Cooler",
    description: "Premium 360mm AIO พร้อม LCD display แสดงอุณหภูมิ ดีไซน์สวยงาม เหมาะสำหรับ showcase build",
    price: 7900,
    imageUrl: "",
    stock: 8,
    attributes: {
      componentType: "CPU Cooler",
      type: "Liquid Cooler",
      socketSupport: ["LGA1700", "LGA1200", "AM5", "AM4"],
      radiatorSize: 360,
    },
  },
  {
    name: "DeepCool AK620 Zero Dark",
    category: "CPU Cooler",
    description: "Dual-tower air cooler ประสิทธิภาพสูง ดีไซน์ all-black เงียบและเย็นเหมาะกับ mid-range build",
    price: 1890,
    imageUrl: "",
    stock: 20,
    attributes: {
      componentType: "CPU Cooler",
      type: "Air Cooler",
      socketSupport: ["LGA1700", "LGA1200", "AM5", "AM4"],
      height: 160,
    },
  },
];

async function seed() {
  console.log(`Seeding ${seedProducts.length} products...`);
  await db.insert(products).values(seedProducts as any[]);
  console.log("Done!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
